# Generated by Django 4.2.2 on 2023-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('favorite_music', models.CharField(choices=[('col', 'Cry of Love'), ('rb', 'Rainbow Bridge'), ('et', 'The Eternal Fire'), ('wh', 'War Heroes')], max_length=50)),
                ('biography', models.TextField()),
            ],
        ),
    ]
