# Generated by Django 4.2.2 on 2023-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rok',
            name='favorite_music',
            field=models.CharField(choices=[('Cry of Love', 'Cry of Love'), ('Rainbow Bridge', 'Rainbow Bridge'), ('The Eternal Fire', 'The Eternal Fire'), ('War Heroes', 'War Heroes')], max_length=50),
        ),
    ]
