# Generated by Django 4.2.2 on 2023-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('favorite_music', models.CharField(choices=[('hl', 'Hello Dolly'), ('jz', 'Jazz Festival'), ('in', 'In Stuttgart'), ('ww', 'What a Wonderful World')], max_length=50)),
                ('biography', models.TextField()),
            ],
        ),
    ]
