# Generated by Django 4.2.2 on 2023-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jazz',
            name='favorite_music',
            field=models.CharField(choices=[('Hello Dolly', 'Hello Dolly'), ('Jazz Festival', 'Jazz Festival'), ('In Stuttgart', 'In Stuttgart'), ('What a Wonderful World', 'What a Wonderful World')], max_length=50),
        ),
    ]
